--CREA TABLA COMO SI FUERA ORACLE
--PASO 1: ELIMINAR LA TABLA SI YA EXISTE
DROP TABLE IF EXISTS VETERINARIA;

--PASO 2 CREAR TABLA
CREATE TABLE VETERINARIA(
	ID_VETERINARIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	NOMBRE NVARCHAR2(100), 
	DIRECCION NVARCHAR2(100), 
	CONTACTO NUMBER, 
	
	CONSTRAINT ID_VETERINARIA_PK PRIMARY KEY (ID_VETERINARIA)
);
