--CREA TABLA COMO SI FUERA ORACLE
--PASO 1: ELIMINAR LA TABLA SI YA EXISTE
DROP TABLE IF EXISTS CLIENTESV;

--PASO 2 CREAR TABLA
CREATE TABLE CLIENTESV(
	ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	NOMBRE NVARCHAR2(100), 
	DIRECCION NVARCHAR2(100), 
	CONTACTO NUMBER, 
	VETERINARIA_ID NUMBER,
	
	CONSTRAINT ID_CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);
